# Generated by Django 4.1.1 on 2025-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('recipient_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('remarks', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TransactionTable',
            },
        ),
    ]
