# Generated by Django 5.2.12 on 2026-03-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nei_control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective'), ('compensating', 'Compensating')], max_length=30)),
                ('description', models.TextField()),
                ('implementation_guidance', models.TextField()),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('partial', 'Partially Implemented'), ('planned', 'Planned'), ('not_implemented', 'Not Implemented')], default='planned', max_length=25)),
                ('effectiveness_score', models.FloatField(default=0.0)),
                ('last_reviewed', models.DateField(auto_now=True)),
                ('implemented_date', models.DateField(blank=True, null=True)),
                ('applicable_assets', models.ManyToManyField(blank=True, to='threats.plantasset')),
                ('mitigates_threats', models.ManyToManyField(blank=True, to='threats.threat')),
            ],
        ),
        migrations.CreateModel(
            name='ControlAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_controls.securitycontrol')),
            ],
        ),
    ]
