# Generated by Django 5.2.12 on 2026-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('scope', models.TextField()),
                ('enforcement_level', models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='mandatory', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Security Policies',
            },
        ),
    ]
