# Generated by Django 5.2.7 on 2026-01-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedresume',
            name='status',
            field=models.CharField(default='present', max_length=20),
        ),
    ]
